import { UpgradeData } from './invisible-rooster.type'

export const INITIAL_UPGRADES_DATA: UpgradeData[] = [
  {
    id: 'eagle-eyes',
    name: 'Olhos de Águia',
    description: 'Aumenta em 1 o número de galos por clique',
    baseCost: 50,
    owned: 0,
    effect: 1,
    type: 'click',
    emoji: '👁️',
  },
  {
    id: 'binoculars',
    name: 'Binóculo de Galináceos',
    description: 'Aumenta em 5 o número de galos por clique',
    baseCost: 250,
    owned: 0,
    effect: 5,
    type: 'click',
    emoji: '🔭',
  },
  {
    id: 'golden-feather',
    name: 'Pluma Dourada',
    description: 'Aumenta em 10 o número de galos por clique',
    baseCost: 1000,
    owned: 0,
    effect: 10,
    type: 'click',
    emoji: '🪶',
  },
  {
    id: 'quantum-coop',
    name: 'Galinheiro Quântico',
    description: 'Produz 1 galo invisível por segundo',
    baseCost: 500,
    owned: 0,
    effect: 1,
    type: 'passive',
    emoji: '🏠',
  },
  {
    id: 'farmhand',
    name: 'Ajuda do Fazendeiro',
    description: 'Produz 5 galos invisíveis por segundo',
    baseCost: 2500,
    owned: 0,
    effect: 5,
    type: 'passive',
    emoji: '👨‍🌾',
  },
  {
    id: 'egg-factory',
    name: 'Fábrica de Ovos',
    description: 'Produz 20 galos invisíveis por segundo',
    baseCost: 10000,
    owned: 0,
    effect: 20,
    type: 'passive',
    emoji: '🥚',
  },
  {
    id: 'alpha-call',
    name: 'Chamado do Galo Alfa',
    description: 'Dobra toda a produção por 30 segundos',
    baseCost: 1000,
    owned: 0,
    effect: 2,
    type: 'multiplier',
    emoji: '👑',
  },
  {
    id: 'rooster-choir',
    name: 'Coro de Galos',
    description: 'Multiplica a produção por 5 por 30 segundos',
    baseCost: 5000,
    owned: 0,
    effect: 5,
    type: 'multiplier',
    emoji: '🎶',
  },
  {
    id: 'mega-sprint',
    name: 'Sprint do Galo',
    description: 'Aumenta em 100 galos por clique durante 10 segundos',
    baseCost: 20000,
    owned: 0,
    effect: 100,
    type: 'multiplier',
    emoji: '⚡',
  },
]
